### ISSUE TITLE
array queries strings attributes contain [], while api doc doesn't

### ISSUE THREAD

**Issue by jorisbontje** [state-of-the-dapps/www_stateofthedapps_com#11]
for example the `tags[]` in `GET /v1/dapps?category=recently+added&refine=nothing&tags[]=luck&text=`

this isn't documented as such however; apiary uses `tags`.

**Comment by robyedlin** [comment]
I think this is a api doc issue.

**Comment by robyedlin** [comment]
BTW, tags are listed as an array, but the api blueprint doesn't allow for the spec to include {?tags[]}
